import test from'node:test';import assert from'node:assert/strict';import{readFileSync,existsSync}from'node:fs';import{dirname,join}from'node:path';import{fileURLToPath}from'node:url';
import{ART_MANIFEST,freedVisualVariant}from'../art.mjs';import{arkoHitProfile,resolveArkoImpact,applyArkoReaction,enemyReactionMotion,createArko,startArkoDive,tickArko}from'../gameplay.mjs';
import{KAEL_POSES,KAEL_POSE_INVARIANTS,validateKaelPoseDefinition,doubleJumpRenderFrame,ANIMATIONS}from'../gameplay.mjs';
test('Kael active pose contract keeps one coherent body with exactly two limbs',()=>{assert.deepEqual(KAEL_POSE_INVARIANTS,{head:1,torso:1,arms:2,hands:2,legs:2,feet:2});for(const pose of KAEL_POSES)assert.equal(validateKaelPoseDefinition(pose),true);for(let i=0;i<ANIMATIONS.doubleJump.frames;i++)assert.equal(doubleJumpRenderFrame(i).rotation,0)});
test('art manifest proves substantive Kael detail contract',()=>{assert.deepEqual(ART_MANIFEST.nativeHeroBox,[52,82]);assert.ok(ART_MANIFEST.kaelFeatures.length>=10);for(const key of['wild-hair','yellow-headband-two-tails','three-alchemy-bottles','skin-hands','large-boots-soles','cream-cuffs','green-pants-to-boots'])assert.ok(ART_MANIFEST.kaelFeatures.includes(key));assert.equal(ART_MANIFEST.frames.walk,24);assert.equal(ART_MANIFEST.frames.sprint,12);assert.equal(ART_MANIFEST.frames.flip,16);assert.equal(ART_MANIFEST.frames.takeoff,8);assert.equal(ART_MANIFEST.frames.jumpUp,6);assert.equal(ART_MANIFEST.frames.fall,6);assert.equal(ART_MANIFEST.frames.land,8);assert.ok(ART_MANIFEST.frames.idle>=8);assert.ok(Object.keys(ART_MANIFEST.palettes).length>=7)});

test('Wonder identity lock: skin hands, cream collar, three distinct belt bottles',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawKaelCompletePose'),src.indexOf('export function drawKaelArt'));assert.match(fn,/P\.skin,P\.o\);px\(g,Math\.round\(p\[2\]\[0\]-2\)/);assert.equal(fn.includes('blob(g,[[p[2][0]-5,p[2][1]-4],[p[2][0]+5,p[2][1]-4],[p[2][0]+6,p[2][1]+4],[p[2][0]-4,p[2][1]+6]],P.leather,P.o)'),false);assert.match(fn,/px\(g,-12\+sideLean\+runShift,-67,24,4,P\.shirt\)/);assert.match(fn,/px\(g,-11\+sideLean\+runShift,-68,22,6,P\.shirt\)/);assert.match(fn,/#49cde0/);assert.match(fn,/#ed5d4c/);assert.match(fn,/#e7d34c/);assert.match(fn,/y\+12/);assert.match(fn,/y\+14/);assert.equal((fn.match(/#49cde0/g)||[]).length,2);assert.equal((fn.match(/#ed5d4c/g)||[]).length,2);assert.equal((fn.match(/#e7d34c/g)||[]).length,2)});

test('Kael poses draw plant-code; no Wonder sheet for idle walk sprint melee or jump',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const gate=src.slice(src.indexOf('export function drawKaelArt'),src.indexOf('/* legacy'));assert.match(gate,/drawKaelCompletePose/);assert.equal(gate.includes('drawWonderKael'),false);assert.equal(gate.includes("pose==='sprint'"),false);assert.equal(gate.includes("pose==='idle'"),false);assert.equal(gate.includes("pose==='walk'"),false);assert.equal(gate.includes("pose==='melee'"),false);const fn=src.slice(src.indexOf('function drawWonderKael'),src.indexOf('export function drawKaelArt'));assert.equal(fn.includes('kael-run.png'),false);assert.equal(fn.includes("if(pose==='sprint')"),false);assert.match(src,/function drawKaelCompletePose/)});


test('Walk and sprint arm counter-swing reads 8px at the hand',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawKaelCompletePose'),src.indexOf('export function drawKaelArt'));assert.match(fn,/Math\.round\(-22-s\*\.75\)/);assert.match(fn,/Math\.round\(26\+s\*\.75\)/);assert.match(fn,/Math\.round\(-s\*1\.4\)/);assert.match(fn,/Math\.round\(s\*1\.4\)/);assert.equal(fn.includes('-24-s*.7'),false);assert.equal(fn.includes('30+s*.7'),false);assert.equal(fn.includes('-16-s*.22'),false);assert.equal(fn.includes('-11-s*.28'),false);assert.match(fn,/1px cream seam so blue arms do not vanish into the blue jacket/);assert.match(fn,/else if\(pose==='doubleJump'\)/);assert.match(fn,/else if\(isJump\)/);assert.match(fn,/1px pupils in the front third/);assert.match(fn,/1px bottle separators, fill stays >=4px/)});
test('Sprint upper-body sway follows render subframes',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawKaelCompletePose'),src.indexOf('export function drawKaelArt'));assert.match(fn,/const motionFrame=Number\.isFinite\(motion\.motionFrame\)\?Math\.max\(0,motion\.motionFrame\):frame/);assert.match(fn,/runPose\?Math\.sin\(motionFrame\*Math\.PI\/6\)\*3\.2/)});
test('Belt bottles have 1px separators and arms have a cream jacket seam',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawKaelCompletePose'),src.indexOf('export function drawKaelArt'));assert.match(fn,/1px bottle separators, fill stays >=4px/);assert.match(fn,/px\(g,-5\+rs,y,1,13,P\.o\)/);assert.match(fn,/px\(g,8\+rs,y-1,1,15,P\.o\)/);assert.match(fn,/px\(g,-6\+rs,y,1,13,P\.o\)/);assert.match(fn,/px\(g,7\+rs,y-1,1,15,P\.o\)/);assert.match(fn,/1px cream seam so blue arms do not vanish into the blue jacket/);assert.match(fn,/drawLimb\(p\[0\],p\[1\],P\.shirt,9\)/);assert.match(fn,/drawLimb\(p\[0\],p\[1\],P\.blue,7\)/);assert.match(fn,/drawLimb\(p\[1\],p\[2\],P\.shirt,8\)/);assert.match(fn,/drawLimb\(p\[1\],p\[2\],P\.blueL,6\)/);assert.equal((fn.match(/#49cde0/g)||[]).length,2);assert.equal((fn.match(/#ed5d4c/g)||[]).length,2);assert.equal((fn.match(/#e7d34c/g)||[]).length,2)});
test('Walk and sprint eyes are 1px front-third pupils with plant lids; idle keeps centered blink',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawKaelCompletePose'),src.indexOf('export function drawKaelArt'));assert.match(fn,/1px pupils in the front third/);assert.match(fn,/pose==='walk'\|\|runPose/);assert.match(fn,/lx\+Math\.floor\(lw\*2\/3\)/);assert.match(fn,/plant=pose==='walk'/);assert.match(fn,/setTransform\(1,0,0,1,0,0\)/);assert.match(fn,/integer device blit so upperSway cannot subpixel-fillRect/);assert.match(fn,/blit\(lx,ey,lw,1,P\.o\)/);assert.equal(fn.includes("px(g,-7+pupilX,headY+7+pupilY,3,3,'#1767a8')"),false);assert.match(fn,/eyesBlink=pose==='idle'&&motion\.eyeState==='EYES_BLINK'/);assert.match(fn,/px\(g,-7\+pupilX,headY\+6\+pupilY,3,4,'#1767a8'\)/)});
test('Sprint trailing knee is plantigrade not a rear hock',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawKaelCompletePose'),src.indexOf('export function drawKaelArt'));assert.equal(fn.includes('STRONGLY OUTWARD-BENT KNEE'),false);assert.equal(fn.includes('outward*kneeBend'),false);assert.equal(fn.includes('shinAngle'),false);assert.match(fn,/Human plantigrade run/);assert.match(fn,/never a rear hock/);assert.match(fn,/useFwd=a>=d/)});
test('Sprint draws plant-code not kael-run.png',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const gate=src.slice(src.indexOf('export function drawKaelArt'),src.indexOf('/* legacy'));assert.equal(gate.includes('drawWonderKael'),false);assert.equal(gate.includes('kael-run.png'),false);assert.match(gate,/drawKaelCompletePose/);const fn=src.slice(src.indexOf('function drawWonderKael'),src.indexOf('export function drawKaelArt'));assert.equal(fn.includes("if(pose==='sprint')"),false);assert.equal(fn.includes('kael-run.png'),false)});
test('Melee draws plant-code not the 8-cell sheet',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawWonderKael'),src.indexOf('export function drawKaelArt'));assert.equal(fn.includes("if(pose==='melee')"),false);assert.equal(src.includes("pose==='melee'?wonderMelee"),false);assert.match(src,/function drawKaelCompletePose/)});
test('Jump takeoff fall land draw plant-code not Wonder sheets',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const gate=src.slice(src.indexOf('export function drawKaelArt'),src.indexOf('/* legacy'));assert.equal(gate.includes("pose==='takeoff'"),false);assert.equal(gate.includes("pose==='jumpUp'"),false);assert.equal(gate.includes("pose==='doubleJump'"),false);assert.equal(gate.includes("pose==='fall'"),false);assert.equal(gate.includes("pose==='land'"),false);assert.match(src,/function drawKaelCompletePose/)});
test('Kael air poses keep green pants to the boot',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function drawKaelCompletePose'),src.indexOf('export function drawKaelArt'));assert.match(fn,/airIdentity=pose==='takeoff'\|\|pose==='jumpUp'\|\|pose==='doubleJump'\|\|pose==='fall'\|\|pose==='land'/);assert.match(fn,/const pants=pose==='idle'\|\|airIdentity/);assert.match(fn,/drawLimb\(knee,boot,pants\?\(back\?'#2d6134':P\.green\):P\.skin,7\)/);assert.match(fn,/px\(g,Math\.round\(knee\[0\]-1\),Math\.round\(knee\[1\]\),3,2,P\.skinL\)/);assert.match(fn,/drawBoot\(boot\[0\],boot\[1\]-10\)/);assert.equal(fn.includes('else if(normalJump)'),false);assert.match(fn,/px\(g,-12\+sideLean\+runShift,-67,24,4,P\.shirt\)/);assert.match(fn,/px\(g,-8,6,20,5,P\.o\)/);assert.match(fn,/px\(g,-6,4,17,2,P\.leatherL\)/)});
test('four enemy silhouettes and rich terrain/decor contracts',()=>{assert.equal(new Set(ART_MANIFEST.enemySilhouettes).size,4);assert.equal(ART_MANIFEST.terrain.dirtVariants,3);assert.ok(ART_MANIFEST.terrain.edgeVariants>=4);assert.ok(ART_MANIFEST.decor.grass>=3);assert.ok(ART_MANIFEST.decor.flowers>=3);assert.ok(ART_MANIFEST.decor.bushes>=2);assert.ok(ART_MANIFEST.decor.trees>=3)});
test('four distinct ordered parallax factors',()=>{const v=Object.values(ART_MANIFEST.parallax);assert.equal(new Set(v).size,4);assert.deepEqual(v,[.04,.11,.23,.37])});
test('Arko damage profile is exact for every pilot enemy',()=>{for(const type of['farmer','animal','brute'])assert.deepEqual(arkoHitProfile(type),{damage:15,stun:1.1,reaction:'stun'});assert.deepEqual(arkoHitProfile('boss'),{damage:8,stun:.35,reaction:'flinch'})});
test('Arko impact is fail-closed for freed or invalid targets',()=>{assert.deepEqual(resolveArkoImpact({alive:true,freed:false,hitbox:true,type:'farmer'}),{damage:15,stun:1.1,reaction:'stun'});assert.deepEqual(resolveArkoImpact({alive:true,freed:false,hitbox:true,type:'boss'}),{damage:8,stun:.35,reaction:'flinch'});assert.equal(resolveArkoImpact({alive:false,type:'farmer'}),null);assert.equal(resolveArkoImpact({alive:true,freed:true,type:'farmer'}),null);assert.equal(resolveArkoImpact({alive:true,hitbox:false,type:'farmer'}),null)});
test('Arko reaction mapping preserves boss flinch instead of full stun',()=>{assert.deepEqual(applyArkoReaction({id:'boss'},arkoHitProfile('boss')),{id:'boss',effect:'flinch',effectTime:.35});assert.deepEqual(applyArkoReaction({id:'farmer'},arkoHitProfile('farmer')),{id:'farmer',effect:'stun',effectTime:1.1})});
test('boss flinch interrupts chase briefly then restores 65 chase speed',()=>{const hit=arkoHitProfile('boss'),boss=applyArkoReaction({type:'boss',hp:80,vx:-180},hit);boss.hp-=hit.damage;const during=enemyReactionMotion(boss.type,boss.effect,boss.effectTime,1,boss.vx),after=enemyReactionMotion(boss.type,boss.effect,0,1,during.vx);assert.equal(boss.hp,72);assert.equal(during.mode,'flinch');assert.notEqual(during.vx,65);assert.ok(Math.abs(during.vx)>=70);assert.deepEqual(after,{vx:65,reacting:false,mode:'chase'})});
test('normal Arko impact deals 15 and holds full stun motion',()=>{const hit=arkoHitProfile('brute'),enemy=applyArkoReaction({type:'brute',hp:50,vx:120},hit);enemy.hp-=hit.damage;assert.equal(enemy.hp,35);assert.deepEqual(enemyReactionMotion(enemy.type,enemy.effect,enemy.effectTime,1,enemy.vx),{vx:0,reacting:true,mode:'stun'})});
test('freed visual flags produce look, speech and evacuation motion variants',()=>{const still=freedVisualVariant({look:false,leaving:false},'farmer',1),look=freedVisualVariant({look:true,leaving:false},'farmer',-1),leave=freedVisualVariant({look:false,leaving:true},'animal',1);assert.deepEqual(still,{look:false,leaving:false,eyeShift:0,step:0,speech:''});assert.equal(look.eyeShift,-2);assert.equal(look.speech,'Danke!');assert.equal(freedVisualVariant({look:true},'boss',1).speech,'Frei!');assert.equal(freedVisualVariant({look:true},'animal',1).speech,'');assert.equal(leave.step,3)});
test('one dive calls hit exactly once then returns and cools down',()=>{const p={x:0,y:100,face:1},target={x:30,y:80,alive:true,type:'farmer'};let a=startArkoDive(createArko(0,80),target,p),hits=0;for(let i=0;i<600;i++)a=tickArko(a,1/120,p,()=>hits++);assert.equal(hits,1);assert.equal(a.state,'ready');assert.equal(a.visible,true);assert.equal(a.uses,1)});
test('Arko impact callback exposes the exact damage profile',()=>{const p={x:0,y:100,face:1},target={x:30,y:80,alive:true,type:'farmer',freed:false,hitbox:true,hp:40};let a=startArkoDive(createArko(0,80),target,p),damage=0;for(let i=0;i<240&&damage===0;i++)a=tickArko(a,1/120,p,t=>{const hit=resolveArkoImpact(t);damage=hit.damage;t.hp-=hit.damage});assert.equal(damage,15);assert.equal(target.hp,25)});

test('cursedShell branches into four readable silhouettes',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function cursedShell'),src.indexOf('export function freedVisualVariant'));assert.match(fn,/type==='farmer'/);assert.match(fn,/type==='animal'/);assert.match(fn,/type==='boss'/);assert.match(fn,/x-18/);assert.match(fn,/y-10/);assert.match(fn,/x\+w\+10/);assert.match(fn,/x-8,y\+30/);assert.equal(fn.includes('const c=[[x-5,y+h]'),false)});

test('drawBottleEffect uses belt colors and three silhouettes not 11x13 squares',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('export function drawBottleEffect'),src.indexOf('export function drawPlantArt')>src.indexOf('export function drawBottleEffect')?src.indexOf('export function drawPlantArt'):src.length);assert.match(fn,/#49cde0/);assert.match(fn,/#ed5d4c/);assert.match(fn,/#e7d34c/);assert.match(fn,/type==='frost'/);assert.match(fn,/type==='ember'/);assert.equal(fn.includes("box(g,x,y,11,13"),false);assert.equal(fn.includes('#55dff2'),false)});

test('drawArkoArt has follow vs dive poses and outline contrast',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('export function drawArkoArt'),src.indexOf('export function drawPlantArt'));assert.match(fn,/state==='dive'/);assert.match(fn,/dive\?0:/);assert.match(fn,/#e8c9a0/);assert.match(fn,/P\.o/);assert.match(fn,/#fff083/)});
test('HUD strip uses icons not ENERGIE/SEITEN/ARKO/type words',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../game.mjs'),'utf8');const hud=src.slice(src.indexOf('function drawHud'),src.indexOf('function draw(){'));assert.equal(src.includes("text('ENERGIE'"),false);assert.equal(src.includes('ARKO BEREIT'),false);assert.equal(src.includes('SEITEN ${'),false);assert.equal(hud.includes('toUpperCase'),false);assert.match(hud,/drawBottleEffect/);assert.match(hud,/drawArkoArt/);assert.match(hud,/drawPageArt/);assert.match(hud,/#f2ad24/);assert.match(hud,/fillRect\(56,21,200,18\)/);assert.match(hud,/fillRect\(370,84,120,4\)/);assert.match(hud,/#4f9b48/);assert.match(hud,/#49d061/);assert.equal(hud.includes('#ed6586'),false);assert.match(hud,/globalAlpha=.42/);assert.match(src,/drawHud\(\);if\(unlock>0\)/)});
test('Arko no-target feedback is short and fades smoothly',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../arko-feedback.mjs'),'utf8');assert.match(src,/event\.code!=='KeyF'/);assert.match(src,/enemy\.alive&&enemy\.active&&enemy\.hostile!==false/);assert.match(src,/until=performance\.now\(\)\+1350/);assert.match(src,/const fade=Math\.min\(1,remaining\/200\)/);assert.match(src,/KEIN ZIEL IN REICHWEITE/)});

test('boss cursedShell uses lord purple and horns above the 70x76 box',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function cursedShell'),src.indexOf('export function freedVisualVariant'));assert.match(fn,/#633a6f/);assert.match(fn,/#513052/);assert.match(fn,/#d08ae6/);assert.match(fn,/y-26/);assert.match(fn,/i<3/);assert.equal(fn.includes('i<7'),false);assert.match(fn,/P\.dark/);assert.match(fn,/#334b39/);const bossPoly=fn.slice(fn.indexOf('const boss='),fn.indexOf('const c='));assert.match(bossPoly,/x-4,y\+h/);assert.equal(bossPoly.includes('y-26'),false)});

test('forest canopies are overlapping leaf blobs not stacked boxes',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('export function drawPixelBackground'),src.indexOf('function dirtTile'));assert.match(fn,/cam\*\.37/);assert.match(fn,/#60452f/);assert.match(fn,/blob\(/);assert.equal(fn.includes('for(const q of[[-10,-3,42]'),false);assert.match(fn,/cam\*\.04/);assert.match(fn,/cam\*\.11/);assert.match(fn,/cam\*\.23/);assert.match(fn,/#459bc7/)});

test('clouds are overlapping puffy blobs not stacked boxes',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('function cloud('),src.indexOf('export function drawPixelBackground'));assert.match(fn,/blob\(/);assert.equal(fn.includes('box(g,x+q[0]'),false);assert.match(src,/i<8;i\+\+\)cloud\(g/);assert.match(src,/cam\*\.04/)});

test('forest leaf masses hang down past hill-box y 352-418',()=>{const src=readFileSync(join(dirname(fileURLToPath(import.meta.url)),'../art.mjs'),'utf8');const fn=src.slice(src.indexOf('export function drawPixelBackground'),src.indexOf('function dirtTile'));assert.match(fn,/cy\+132/);assert.match(fn,/cam\*\.37/);assert.match(fn,/for\(let q=0;q<4;q\+\+\)box\(g,x\+25\+q\*39,370-\(q%2\)\*18,42,48/)});
