import test from'node:test';import assert from'node:assert/strict';
import{ANIMATIONS,KAEL_POSES,horizontalMotion,animationFrame,animationPhase,canMeleeDamage,canDoubleJump,kaelRenderFrame,doubleJumpRenderFrame,facingTransform,beginLiberation,liberationMode,enemyRenderClass,evacuationStep,groundAt,scanGap}from'../gameplay.mjs';
import{advanceLiberation}from'../rules.mjs';
function run(seconds,hz,input,start={vx:0,face:1}){let b={...start};for(let i=0;i<seconds*hz;i++)b={...b,...horizontalMotion(b,input,1/hz)};return b}
test('Bewegung ist bei 30/60/120 Hz praktisch identisch',()=>{const v=[30,60,120].map(h=>run(.2,h,{axis:1,sprint:false,onGround:true,knockback:0}).vx);assert.ok(Math.max(...v)-Math.min(...v)<.001)});
test('Beschleunigung, Bremsung, Turn und Air-Control sind direkt aber weich',()=>{let b=run(.05,60,{axis:1,onGround:true,knockback:0});assert.ok(b.vx>0&&b.vx<190);assert.ok(run(.05,60,{axis:0,onGround:true,knockback:0},{vx:190,face:1}).vx<100);assert.ok(run(.1,60,{axis:-1,onGround:true,knockback:0},{vx:190,face:1}).vx<0);assert.ok(run(.1,60,{axis:1,onGround:false,knockback:0}).vx<100)});
test('Knockback wird nicht überschrieben',()=>{assert.deepEqual(horizontalMotion({vx:-300,face:1},{axis:1,onGround:true,knockback:.1},.016),{vx:-300,face:1})});
test('Walk/Sprint besitzen 24/8 klar getrennte Schrittframes und passende FPS',()=>{assert.equal(ANIMATIONS.walk.frames,24);assert.equal(ANIMATIONS.sprint.frames,8);assert.equal(ANIMATIONS.walk.fps,24);assert.ok(ANIMATIONS.sprint.fps>=14&&ANIMATIONS.sprint.fps<=18);assert.deepEqual([...new Set(Array.from({length:24},(_,i)=>animationFrame('walk',i/24)))],Array.from({length:24},(_,i)=>i))});
test('Kaels Oberkörper hat lebendige, subtile Zyklusbewegung',()=>{assert.deepEqual([0,1,2,3].map(i=>kaelRenderFrame('idle',i).upperY),[0,-1,0,1]);assert.notDeepEqual([0,1,2,3].map(i=>kaelRenderFrame('walk',i).upperY),[0,0,0,0]);assert.notDeepEqual([0,1,2,3].map(i=>kaelRenderFrame('sprint',i).upperY),[0,0,0,0]);assert.equal(kaelRenderFrame('walk',0).legs[0],-12)});
test('Kael stride exposes articulated knees, boots and face cadence',()=>{const walk=Array.from({length:24},(_,i)=>kaelRenderFrame('walk',i));const sprint=Array.from({length:8},(_,i)=>kaelRenderFrame('sprint',i));assert.ok(new Set(walk.map(f=>f.legs.join(','))).size>=10);assert.ok(new Set(sprint.map(f=>f.legs.join(','))).size>=7);assert.ok(walk.some(f=>f.bootBottoms.includes(0))&&sprint.some(f=>f.bootBottoms.includes(0)));assert.equal(kaelRenderFrame('idle',2).blink,true);assert.equal(kaelRenderFrame('idle',0).blink,false)});
test('Walk/Sprint bleiben vorwaerts lesbar und spiegeln nur die Grafik',()=>{const w0=kaelRenderFrame('walk',0),w12=kaelRenderFrame('walk',12),s0=kaelRenderFrame('sprint',0),s5=kaelRenderFrame('sprint',5);assert.ok(w0.legs[2]>w0.legs[0],'rechter Kontaktfuss steht vorne');assert.ok(w12.legs[0]>w12.legs[2],'linker Kontaktfuss uebernimmt vorne');assert.ok(w0.armSwing<0&&w12.armSwing>0,'Arme schwingen gegenlaeufig');assert.ok(s0.armSwing<0&&s5.armSwing>0,'Sprintarme schwingen gegenlaeufig');assert.equal(animationFrame('walk',.25),6);assert.equal(animationFrame('walk',.25),animationFrame('walk',.25),'Facing darf Zeit nicht invertieren');assert.equal(facingTransform(-1,15).scaleX,-1)});
test('Jump chain has takeoff/jumpUp/fall/land in-betweens',()=>{assert.deepEqual([ANIMATIONS.takeoff.frames,ANIMATIONS.takeoff.fps],[8,18]);assert.deepEqual([ANIMATIONS.jumpUp.frames,ANIMATIONS.jumpUp.fps],[6,16]);assert.deepEqual([ANIMATIONS.fall.frames,ANIMATIONS.fall.fps],[6,16]);assert.deepEqual([ANIMATIONS.land.frames,ANIMATIONS.land.fps],[8,18]);assert.equal(ANIMATIONS.doubleJump.frames,10);assert.equal(ANIMATIONS.doubleJump.fps,12);const takeoff=Array.from({length:8},(_,i)=>kaelRenderFrame('takeoff',i));const jump=Array.from({length:6},(_,i)=>kaelRenderFrame('jumpUp',i));const fall=Array.from({length:6},(_,i)=>kaelRenderFrame('fall',i));const land=Array.from({length:8},(_,i)=>kaelRenderFrame('land',i));assert.ok(new Set(takeoff.map(f=>f.legs.join(','))).size>=4);assert.ok(new Set(jump.map(f=>f.legs.join(','))).size>=5);assert.ok(new Set(fall.map(f=>f.legs.join(','))).size>=5);assert.ok(new Set(land.map(f=>f.legs.join(','))).size>=4);assert.deepEqual(takeoff.slice(0,3).map(f=>f.upperY),[5,5,5]);assert.deepEqual(takeoff.slice(3).map(f=>f.upperY),[2,2,2,2,2]);assert.deepEqual(land.slice(0,3).map(f=>f.upperY),[5,5,5]);assert.deepEqual(land.slice(3).map(f=>f.upperY),[2,2,2,2,2]);assert.notDeepEqual(jump[0].legs,jump[5].legs);assert.notDeepEqual(fall[0].legs,fall[5].legs)});
test('Doppelsprung ist einmalig, edge-sicher und als aufrechter Air-Boost animiert',()=>{assert.equal(ANIMATIONS.doubleJump.frames,10);assert.equal(ANIMATIONS.doubleJump.loop,false);const airborne={on:false,doubleJumpUsed:false,hitTime:0,duck:false};assert.equal(canDoubleJump(airborne),true);assert.equal(canDoubleJump({...airborne,doubleJumpUsed:true}),false);assert.equal(canDoubleJump({...airborne,on:true}),false);assert.equal(canDoubleJump({...airborne,duck:true}),false);assert.equal(canDoubleJump({...airborne,hitTime:.1}),false);const frames=Array.from({length:10},(_,i)=>doubleJumpRenderFrame(i));assert.equal(new Set(frames.map(f=>f.legs.join(','))).size,10);assert.ok(frames.every(f=>f.rotation===0));assert.notEqual(frames[0].armSwing,frames[5].armSwing);assert.notDeepEqual(frames[0].legs,frames[5].legs)});
test('Aktionen haben Windup, Active/Release, Recover',()=>{assert.deepEqual([...new Set(ANIMATIONS.melee.phases)],['windup','active','recover']);assert.deepEqual([...new Set(ANIMATIONS.throw.phases)],['windup','release','recover']);assert.equal(animationPhase('throw',2),'release')});
test('Melee-Schaden verlangt Pose, laufenden Angriff, aktive Phase und neue ID',()=>{const active={pose:'melee',attack:.2,animTime:2/15,attackId:4};assert.equal(canMeleeDamage(active,3),true);assert.equal(canMeleeDamage({...active,pose:'idle'},3),false);assert.equal(canMeleeDamage({...active,pose:'walk'},3),false);assert.equal(canMeleeDamage({...active,attack:0},3),false);assert.equal(canMeleeDamage({...active,animTime:0},3),false);assert.equal(canMeleeDamage(active,4),false)});
test('Kaels visueller Fußanker bleibt in allen Posen und Facings fix',()=>{for(const pose of KAEL_POSES)for(let frame=0;frame<ANIMATIONS[pose].frames;frame++)for(const face of[-1,1]){const m=kaelRenderFrame(pose,frame);assert.ok(m.bootBottoms.every(y=>y<=0),`${pose}/${frame}/${face}`)}for(const pose of['walk','sprint'])for(const frame of[0,4])assert.ok(kaelRenderFrame(pose,frame).bootBottoms.includes(0),`${pose}/${frame}`)});
test('Befreiung ist atomar und nie wieder cursed',()=>{const e=beginLiberation({alive:true,hp:1,state:'hostile',hostile:true,hitbox:true});assert.deepEqual([e.alive,e.freed,e.state,e.hostile,e.hitbox],[false,true,'liberating',false,false]);assert.equal(liberationMode(e),'normal');assert.equal(liberationMode({...e,state:'despawned'}),'hidden')});
test('Freed-Rendersequenz trennt Hüllenbruch, Wolke, Normalform und Despawn',()=>{const base={alive:false,freed:true,state:'liberating'};for(const phase of['crack','cloud']){const r=enemyRenderClass({...base,liberation:{phase}});assert.equal(r.drawNormal,false,phase);assert.equal(r.drawCursed,false,phase);assert.equal(r.hidden,false,phase);assert.equal(phase==='crack'?r.drawShell:r.drawCloud,true,phase)}for(const phase of['normal','look','exit','done']){const r=enemyRenderClass({...base,state:'evacuating',liberation:{phase}});assert.equal(r.drawNormal,true,phase);assert.equal(r.drawCursed,false,phase);assert.equal(r.hidden,false,phase)}const hidden=enemyRenderClass({...base,state:'despawned',liberation:{phase:'done'}});assert.equal(hidden.hidden,true);assert.equal(hidden.drawNormal,false);assert.equal(hidden.drawCursed,false)});
const flat=[[0,100,400,40]],small=[[0,100,100,40],[150,100,250,40]],large=[[0,100,100,40],[240,100,160,40]],upper=[[0,100,100,20],[160,100,200,20]];
test('Ground-Probe erkennt Boden und Lücken',()=>{assert.equal(groundAt(flat,50,100),true);assert.ok(scanGap(small,105,100,1)<=80);assert.equal(scanGap(large,105,100,1),Infinity)});
test('Mensch/Tier planen verschiedene Geschwindigkeit ohne Position doppelt zu bewegen',()=>{const b={freed:true,state:'evacuating',x:20,y:50,w:30,h:50,on:true,evacDir:1,visible:true};const h=evacuationStep({...b,type:'farmer'},flat,.1,400),a=evacuationStep({...b,type:'animal'},flat,.1,400);assert.equal(h.x,b.x);assert.equal(a.x,b.x);assert.equal(h.vx,120);assert.equal(a.vx,185);assert.equal(h.hostile,false);assert.equal(a.hitbox,false)});
test('Eine Sekunde Integration entspricht exakt einfacher Evakuierungsgeschwindigkeit',()=>{for(const[type,speed]of[['farmer',120],['animal',185]]){let e={freed:true,state:'evacuating',type,x:20,y:50,w:30,h:50,on:true,evacDir:1,visible:true};for(let i=0;i<60;i++){e=evacuationStep(e,[[0,100,2000,40]],1/60,2000,0,2000);e.x+=e.vx/60}assert.ok(Math.abs(e.x-20-speed)<1e-9,type)}});
test('Kleine Lücke wird gesprungen, große gemieden, erhöhte unterstützt',()=>{const b={freed:true,state:'evacuating',type:'farmer',x:60,y:50,w:30,h:50,on:true,evacDir:1,visible:true};assert.ok(evacuationStep(b,small,.016,400).vy<0);const blocked=evacuationStep(b,large,.016,400);assert.equal(blocked.evacDir,-1);assert.equal(blocked.x,b.x);assert.ok(evacuationStep(b,upper,.016,400).vy<0)});
test('Despawn erst außerhalb des Sichtbereichs und nach done',()=>{const b={freed:true,hostile:false,state:'evacuating',type:'animal',x:1045,y:50,w:30,h:50,on:true,evacDir:1,visible:true,liberation:{phase:'done',remaining:0}};const e=evacuationStep(b,[[0,100,1200,20]],.1,1200,0,960);assert.equal(e.state,'despawned');assert.equal(e.visible,false);assert.equal(e.hostile,false)});
test('vollständige Befreiungsfolge bleibt bis done sichtbar und normal',()=>{let e=beginLiberation({alive:true,hp:1,type:'farmer',x:1045,y:50,w:30,h:50,on:true,evacDir:1,visible:true,hostile:true,hitbox:true});const phases=['crack'];for(const dt of[.7,1.1,.55,.8]){e.liberation=advanceLiberation(e.liberation,dt);phases.push(e.liberation.phase)}assert.deepEqual(phases,['crack','cloud','normal','look','exit']);e.state='evacuating';const early=evacuationStep(e,[[0,100,1200,20]],.1,1200,0,960);assert.equal(early.state,'evacuating');assert.equal(early.visible,true);assert.equal(early.freed,true);assert.equal(early.hostile,false);assert.equal(enemyRenderClass(early).drawNormal,true);early.liberation=advanceLiberation(early.liberation,1);assert.equal(early.liberation.phase,'done');const gone=evacuationStep(early,[[0,100,1200,20]],.1,1200,0,960);assert.equal(gone.state,'despawned');assert.equal(gone.visible,false);assert.equal(gone.freed,true);assert.equal(gone.hostile,false)});

test('Walk bleibt Side-View auch mit Facing, kein Right-Run',()=>{const a=kaelRenderFrame('walk',0,1),b=kaelRenderFrame('walk',0,0);assert.deepEqual(a.legs,b.legs);assert.equal(a.legs[0],-12);assert.equal(a.pelvisX||0,0);assert.equal(a.lean,0)});